# Nome do pacote/app Flutter.
name: frontend_flutter
# Descricao visivel em ferramentas do ecossistema.
description: Frontend Flutter do projeto
publish_to: "none"
version: 0.1.0+1

environment:
  # Versao minima e maxima do Dart suportadas por este projeto.
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # SDK principal do Flutter.
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_tts: ^4.2.2
  sqflite: ^2.4.1
  path: ^1.9.1
  audioplayers: ^6.1.0
  file_picker: ^8.1.2
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.4
  url_launcher: ^6.3.1
  android_intent_plus: ^5.3.0
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  crypto: ^3.0.6
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  battery_plus: ^6.0.2
  image_picker: ^1.1.2
  pdf: ^3.11.1
  printing: ^5.14.0
  # Reconhecimento de fala (microfone -> texto).
  speech_to_text: ^7.0.0
  geolocator: ^13.0.2
  # Tipografia mais profissional para o painel.
  google_fonts: ^6.2.1

dev_dependencies:
  # Biblioteca de testes padrao para Flutter.
  flutter_test:
    sdk: flutter
  # Regras de lint para manter o codigo mais limpo.
  flutter_lints: ^5.0.0

flutter:
  # Habilita uso dos icones Material Design.
  uses-material-design: true
  assets:
    - assets/giphy3.gif
